CREATE DATABASE IF NOT EXISTS review_app_db;

CREATE TABLE CLIENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL varchar(50)
);

CREATE TABLE SENTIMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TEXT VARCHAR(50),
    TYPE VARCHAR(10) NOT NULL,
    CLIENT_ID INT NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);

